# Chunk Generation Configuration (Don't change if you are editing/updating existing data)
seed = 8221611027149008269
chunk_radius_center_x = 0
chunk_radius_center_z = 0
chunk_radius_circular = true
chunk_batch_size = 10000

# (Can change)
chunk_radius_start_index = 0
chunk_radius_start = 0
chunk_radius_end = 250


# Zarr storage settings (Don't change if you are editing/updating existing data)
zarr_enabled = true
zarr_storage_location = "./.zarr_data"
zarr_chunk_region_size = 64
zarr_compression = "zstd"  # "none", "gzip", "zstd"
zarr_compression_level = 3