version: '3.8'

services:
  postgres:
    container_name: fpostgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passord01
      - POSTGRES_DB=ekko
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data/

  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    # Link and environment allow pgweb to connect to Postgres
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:Passord01@postgres:5432/ekko?sslmode=disable

volumes:
  data: