version: '3.8'

services:
  candle-gpu:
    build:
      context: ..  # Root of your workspace
      dockerfile: ./ekko-location/Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all